### ISSUE TITLE
-e option not work

### ISSUE THREAD

**Issue by bded** [orhun/k3rmit#11]
I just try to start the k3rmit -e micro command, but it returns with bus error(coredump).
I try my all consol app (lf mg mc) with same error.
But if I open k3rmit and then start this apps everything is OK.
Is this option implemented?

FreeBSD and k3rmit 2.1 build from source.

**Comment by orhun** [comment]
Can you give more details about the commands that you tried to run with k3rmit via `-e` option?
Are they CLI applications or do they have a graphical interface?
k3rmit basically tries to run the given command with the [shell](https://github.com/orhun/k3rmit/blob/master/src/k3rmit.c#L461) at the startup. `-c` option of the shell might be the problem.

**Comment by bded** [comment]
As I wrote, all apps are CLI (mc midnight commander, lf file manager, mg editor).At first I want to start this from I3 wm with keybind." bindsym $super+l exec k3rmit -e lf "
 Neither works . Then I try test in the other terminal (alacritty) start with k3rmit -e lf, or k3rmit -e mg commands and it return with Bus error(coredump)

**Comment by travankor** [comment]
@orhun 

Here is a backtrace

<details>

```
GNU gdb (GDB) 9.1
Copyright (C) 2020 Free Software Foundation, Inc.                                                                                                                                                                                               
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/k3rmit...
Reading symbols from /usr/lib/debug//usr/bin/k3rmit...
[New LWP 19346]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `k3rmit -e ls'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fa45099b56d in g_execute (search_path_from_envp=0, search_path=0, envp=0x7fa44000dff0, argv=0x55f53f3fead0, file=0x0) at ../src/vtespawn.cc:1101
1101    ../src/vtespawn.cc: No such file or directory.
(gdb) bt full
#0  0x00007fa45099b56d in g_execute (search_path_from_envp=0, search_path=0, envp=0x7fa44000dff0, argv=0x55f53f3fead0, file=0x0) at ../src/vtespawn.cc:1101
No locals.
#1  do_exec (user_data=0x55f53f548140, child_setup=0x7fa450961900 <vte::base::pty_child_setup_cb(void*)>, file_and_argv_zero=0, child_inherits_stdin=<optimized out>, stderr_to_null=0, stdout_to_null=0, search_path_from_envp=0, 
    search_path=0, close_descriptors=1, envp=0x7fa44000dff0, argv=0x55f53f3fead0, working_directory=0x0, stderr_fd=<optimized out>, stdout_fd=<optimized out>, stdin_fd=<optimized out>, child_err_report_fd=<optimized out>)
    at ../src/vtespawn.cc:704
        __PRETTY_FUNCTION__ = <optimized out>
        read_null = <optimized out>
        _g_boolean_var_ = <optimized out>
        write_null = <optimized out>
        _g_boolean_var_ = <optimized out>
        write_null = <optimized out>
#2  fork_exec_with_pipes (error=0x7fa44ce4b390, pollfd=0x0, timeout=-1, standard_error=0x0, standard_output=0x0, standard_input=<optimized out>, child_pid=0x7fa44ce4b380, user_data=0x55f53f548140, 
    child_setup=0x7fa450961900 <vte::base::pty_child_setup_cb(void*)>, cloexec_pipes=0, file_and_argv_zero=0, child_inherits_stdin=<optimized out>, stderr_to_null=0, stdout_to_null=0, search_path_from_envp=0, search_path=0, 
    close_descriptors=1, envp=0x7fa44000dff0, argv=0x55f53f3fead0, working_directory=0x0, intermediate_child=0) at ../src/vtespawn.cc:924
        pid = <optimized out>
        stderr_pipe = {-1, -1}
        pipe_flags = 0
        stdin_pipe = {-1, -1}
        stdout_pipe = {-1, -1}
        child_err_report_pipe = {-1, 15}
        child_pid_report_pipe = <optimized out>
        pid = <optimized out>
        stdin_pipe = <optimized out>
        stdout_pipe = <optimized out>
        stderr_pipe = <optimized out>
        child_err_report_pipe = <optimized out>
        child_pid_report_pipe = <optimized out>
        pipe_flags = <optimized out>
        __PRETTY_FUNCTION__ = <optimized out>
        _g_boolean_var_ = <optimized out>
        errsv = <optimized out>
        buf = <optimized out>
        n_ints = <optimized out>
#3  vte_spawn_async_with_pipes_cancellable (working_directory=working_directory@entry=0x0, argv=argv@entry=0x55f53f3fea
    child_setup=child_setup@entry=0x7fa450961900 <vte::base::pty_child_setup_cb(void*)>, user_data=user_data@entry=0x55
    pollfd=0x0, error=0x7fa44ce4b390) at ../src/vtespawn.cc:221
        __PRETTY_FUNCTION__ = "gboolean vte_spawn_async_with_pipes_cancellable(const gchar*, gchar**, gchar**, GSpawnFl
#4  0x00007fa450961d48 in vte::base::Pty::spawn (this=0x55f53f548140, directory=directory@entry=0x0, argv=argv@entry=0x
    child_setup_func=child_setup_func@entry=0x0, child_setup_data=0x0, child_pid=0x7fa44ce4b4ac, timeout=-1, cancellabl
        spawn_flags = 2
        ret = true
        inherit_envv = true
        envp2 = 0x7fa44000dff0
        i = <optimized out>
        pollfd = {fd = 0, events = 0, revents = 0}
        pid = -1
        err = {m_error = 0x0}
#5  0x00007fa450962d7f in _vte_pty_spawn (pty=0x55f53f4b6050, directory=0x0, argv=0x55f53f3fead0, envv=0x0, spawn_flags
    error=0x7fa44ce4b4b0) at ../src/vtepty.cc:188
        __PRETTY_FUNCTION__ = "gboolean _vte_pty_spawn(VtePty*, const char*, char**, char**, GSpawnFlags, GSpawnChildSe
        impl = <optimized out>
#6  0x00007fa450962e5b in async_spawn_run_in_thread (task=0x55f53f34fbd0, object=<optimized out>, data_=<optimized out>
        data = <optimized out>
        pid = 22005
        error = 0x0
#7  0x00007fa44fc1419e in g_task_thread_pool_thread (thread_data=0x55f53f34fbd0, pool_data=<optimized out>) at ../gio/g
        task = 0x55f53f34fbd0
#8  0x00007fa450a09174 in g_thread_pool_thread_proxy (data=<optimized out>) at ../glib/gthreadpool.c:308
        task = 0x55f53f34fbd0
        pool = <optimized out>
#9  0x00007fa450a0fb3d in g_thread_proxy (data=0x55f53f357c50) at ../glib/gthread.c:805
--Type <RET> for more, q to quit, c to continue without paging--
        thread = 0x55f53f357c50
        __FUNCTION__ = "g_thread_proxy"
#10 0x00007fa44f5e0f27 in start_thread (arg=<optimized out>) at pthread_create.c:479
        ret = <optimized out>
        pd = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140343641462528, -5051918056754184281, 140727328004542, 14072732800
              0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = 0
#11 0x00007fa450885e0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
(gdb) quit
```
